export const testmap = {
  "id": 7188,
  "username": "elena",
  "parentId": 0,
  "rootId": 0,
  "topicId": 17,
  "isRoot": true,
  "isPublic": false,
  "isRecap": false,
  "name": "Webpack",
  "importance": 1,
  "levels": 4,
  "difficulty": 0,
  "position": null,
  "notabene": false,
  "text": "A build tool for JavaScript. sdsdf\n\nThe current <b>version</b> is 5.\n\nWebpack has a <b>CLI tool</b> and a <b>dev server</b>.\n\nExample <b>package.json</b> config:\n\n<pre><code class=\"language-jsx\">\"webpack\": \"^5.94.0\",\n\"webpack-cli\": \"^5.0.1\",\n\"webpack-dev-server\": \"^5.0.4\"</code></pre>",
  "questions": null,
  "counter": 18,
  "maps": [
    {
      "id": 7189,
      "username": "elena",
      "parentId": 7188,
      "rootId": 7188,
      "topicId": 0,
      "isRoot": false,
      "isPublic": false,
      "isRecap": false,
      "name": "Config",
      "importance": 1,
      "levels": 1,
      "difficulty": 0,
      "position": null,
      "notabene": false,
      "text": null,
      "questions": null,
      "counter": 1,
      "maps": [
        {
          "id": 7190,
          "username": "elena",
          "parentId": 7189,
          "rootId": 7188,
          "topicId": 0,
          "isRoot": false,
          "isPublic": false,
          "isRecap": false,
          "name": "CLI",
          "importance": 1,
          "levels": 0,
          "difficulty": 0,
          "position": null,
          "notabene": false,
          "text": null,
          "questions": null,
          "counter": 0,
          "maps": null
        }
      ]
    },
    {
      "id": 7198,
      "username": "elena",
      "parentId": 7188,
      "rootId": 7188,
      "topicId": 0,
      "isRoot": false,
      "isPublic": false,
      "isRecap": false,
      "name": "Network address",
      "importance": 1,
      "levels": 0,
      "difficulty": 0,
      "position": null,
      "notabene": true,
      "text": "Webpack will automatically provide an IP address from which we can open the project on <b>another device</b> that is connected to the <b>same network</b> (i.e. home WiFi).\n\nThe address will be printed in the starting message.\n\nExample: <pre><code class=\"language-jsx\">[webpack-dev-server] On Your Network (IPv4): <a href=\"http://192.168.0.59:9000/</code></pre>\" target=\"_blank\">http://192.168.0.59:9000/</code></pre></a>",
      "questions": null,
      "counter": 0,
      "maps": null
    },
    {
      "id": 7276,
      "username": "elena",
      "parentId": 7188,
      "rootId": 7188,
      "topicId": 0,
      "isRoot": false,
      "isPublic": false,
      "isRecap": true,
      "name": "Webpack dev server",
      "importance": 1,
      "levels": 1,
      "difficulty": 0,
      "position": null,
      "notabene": false,
      "text": "sdfsdf\nsdfsdf\nsdf\n\ntest",
      "questions": null,
      "counter": 1,
      "maps": [
        {
          "id": 7287,
          "username": "elena",
          "parentId": 7276,
          "rootId": 7188,
          "topicId": 0,
          "isRoot": false,
          "isPublic": false,
          "isRecap": true,
          "name": "Test",
          "importance": 1,
          "levels": 0,
          "difficulty": 0,
          "position": null,
          "notabene": false,
          "text": null,
          "questions": null,
          "counter": 0,
          "maps": null
        }
      ]
    },
    {
      "id": 7288,
      "username": "elena",
      "parentId": 7188,
      "rootId": 7188,
      "topicId": 0,
      "isRoot": false,
      "isPublic": false,
      "isRecap": true,
      "name": "Test 2",
      "importance": 1,
      "levels": 0,
      "difficulty": 0,
      "position": null,
      "notabene": false,
      "text": null,
      "questions": null,
      "counter": 0,
      "maps": null
    },
    {
      "id": 7332,
      "username": "elena",
      "parentId": 7188,
      "rootId": 7188,
      "topicId": 0,
      "isRoot": false,
      "isPublic": false,
      "isRecap": true,
      "name": "ttt",
      "importance": 1,
      "levels": 1,
      "difficulty": 0,
      "position": null,
      "notabene": false,
      "text": null,
      "questions": null,
      "counter": 2,
      "maps": [
        {
          "id": 7331,
          "username": "elena",
          "parentId": 7332,
          "rootId": 7188,
          "topicId": 0,
          "isRoot": false,
          "isPublic": false,
          "isRecap": true,
          "name": "Test",
          "importance": 1,
          "levels": 0,
          "difficulty": 0,
          "position": null,
          "notabene": false,
          "text": null,
          "questions": null,
          "counter": 0,
          "maps": null
        },
        {
          "id": 7333,
          "username": "elena",
          "parentId": 7332,
          "rootId": 7188,
          "topicId": 0,
          "isRoot": false,
          "isPublic": false,
          "isRecap": true,
          "name": "zsddfds",
          "importance": 1,
          "levels": 0,
          "difficulty": 0,
          "position": null,
          "notabene": false,
          "text": null,
          "questions": null,
          "counter": 0,
          "maps": null
        }
      ]
    },
    {
      "id": 7334,
      "username": "elena",
      "parentId": 7188,
      "rootId": 7188,
      "topicId": 0,
      "isRoot": false,
      "isPublic": false,
      "isRecap": true,
      "name": "sdfsdf",
      "importance": 1,
      "levels": 1,
      "difficulty": 0,
      "position": null,
      "notabene": false,
      "text": null,
      "questions": null,
      "counter": 1,
      "maps": [
        {
          "id": 7336,
          "username": "elena",
          "parentId": 7334,
          "rootId": 7188,
          "topicId": 0,
          "isRoot": false,
          "isPublic": false,
          "isRecap": true,
          "name": "sddsf",
          "importance": 1,
          "levels": 0,
          "difficulty": 0,
          "position": null,
          "notabene": false,
          "text": null,
          "questions": null,
          "counter": 0,
          "maps": null
        }
      ]
    },
    {
      "id": 7191,
      "username": "elena",
      "parentId": 7188,
      "rootId": 7188,
      "topicId": 0,
      "isRoot": false,
      "isPublic": false,
      "isRecap": false,
      "name": "Dev server",
      "importance": 2,
      "levels": 3,
      "difficulty": 0,
      "position": null,
      "notabene": false,
      "text": "<a href=\"https://www.npmjs.com/package/webpack-dev-server\" target=\"_blank\">https://www.npmjs.com/package/webpack-dev-server</a>\n\n<pre><code class=\"language-jsx\">npm install webpack-dev-server --save-dev</code></pre>\n\nRun Webpack dev server with Webpack CLI:\n\n<pre><code class=\"language-jsx\">npx webpack serve</code></pre>\n\nThis command will pick <b>default config</b> file with the name <code class=\"language-jsx\">webpack.config.js</code>. \n\nThis command <b>doesn't need</b> an explicit configuration for the development server - it will pick <b>static files</b> from the <code class=\"language-jsx\">/public</code> directory.",
      "questions": null,
      "counter": 6,
      "maps": [
        {
          "id": 7192,
          "username": "elena",
          "parentId": 7191,
          "rootId": 7188,
          "topicId": 0,
          "isRoot": false,
          "isPublic": false,
          "isRecap": false,
          "name": "devServer",
          "importance": 2,
          "levels": 2,
          "difficulty": 0,
          "position": null,
          "notabene": false,
          "text": "<code class=\"language-jsx\">devServer</code> is the field in <code class=\"language-jsx\">webpack.config.js</code> used to add the server configuration.\n\n<pre><code class=\"language-jsx\">module.exports = {\n  // ...\n  devServer: {\n    // ...\n  },\n};</code></pre>",
          "questions": null,
          "counter": 4,
          "maps": [
            {
              "id": 7193,
              "username": "elena",
              "parentId": 7192,
              "rootId": 7188,
              "topicId": 0,
              "isRoot": false,
              "isPublic": false,
              "isRecap": false,
              "name": "static",
              "importance": 2,
              "levels": 1,
              "difficulty": 0,
              "position": null,
              "notabene": false,
              "text": "An option to configure the way to serve <b>static files</b>.\n\n<a href=\"https://webpack.js.org/configuration/dev-server/#devserverstatic\" target=\"_blank\">https://webpack.js.org/configuration/dev-server/#devserverstatic</a>",
              "questions": null,
              "counter": 1,
              "maps": [
                {
                  "id": 7194,
                  "username": "elena",
                  "parentId": 7193,
                  "rootId": 7188,
                  "topicId": 0,
                  "isRoot": false,
                  "isPublic": false,
                  "isRecap": false,
                  "name": "directory",
                  "importance": 2,
                  "levels": 0,
                  "difficulty": 0,
                  "position": null,
                  "notabene": false,
                  "text": "Set the path to the static files directory:\n\n<pre><code class=\"language-jsx\">devServer: {\n  static: {\n    // serve static files from the \"dist\" directory\n    directory: path.join(__dirname, 'dist'),\n  }\n}</code></pre>",
                  "questions": null,
                  "counter": 0,
                  "maps": null
                }
              ]
            },
            {
              "id": 7195,
              "username": "elena",
              "parentId": 7192,
              "rootId": 7188,
              "topicId": 0,
              "isRoot": false,
              "isPublic": false,
              "isRecap": false,
              "name": "port",
              "importance": 2,
              "levels": 0,
              "difficulty": 0,
              "position": null,
              "notabene": false,
              "text": "Set port:\n\n<pre><code class=\"language-jsx\">devServer: {\n  port: 9000\n}</code></pre>",
              "questions": null,
              "counter": 0,
              "maps": null
            },
            {
              "id": 7196,
              "username": "elena",
              "parentId": 7192,
              "rootId": 7188,
              "topicId": 0,
              "isRoot": false,
              "isPublic": false,
              "isRecap": false,
              "name": "compress",
              "importance": 3,
              "levels": 0,
              "difficulty": 0,
              "position": null,
              "notabene": false,
              "text": "Enable <b>gzip compression</b> for everything served:\n\n<pre><code class=\"language-jsx\">devServer: {\n  compress: true,\n}</code></pre>",
              "questions": null,
              "counter": 0,
              "maps": null
            }
          ]
        },
        {
          "id": 7197,
          "username": "elena",
          "parentId": 7191,
          "rootId": 7188,
          "topicId": 0,
          "isRoot": false,
          "isPublic": false,
          "isRecap": false,
          "name": "Errors",
          "importance": 3,
          "levels": 0,
          "difficulty": 0,
          "position": null,
          "notabene": false,
          "text": "If you open a page and see <b>\"Cannot GET /\"</b> message, it means that the <b>folder</b> from which Webpack serves static files is <b>empty</b> or <b>doesn't exist</b>.",
          "questions": null,
          "counter": 0,
          "maps": null
        }
      ]
    }
  ]
}